//
// Generated file, do not edit! Created by nedtool 5.0 from nwkTree/address_appointment.msg.
//

#ifndef __ADDRESS_APPOINTMENT_M_H
#define __ADDRESS_APPOINTMENT_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>nwkTree/address_appointment.msg:16</tt> by nedtool.
 * <pre>
 * message addressAppointment
 * {
 *     int firstAddress;
 *     int lastAddress;
 * }
 * </pre>
 */
class addressAppointment : public ::omnetpp::cMessage
{
  protected:
    int firstAddress;
    int lastAddress;

  private:
    void copy(const addressAppointment& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const addressAppointment&);

  public:
    addressAppointment(const char *name=nullptr, int kind=0);
    addressAppointment(const addressAppointment& other);
    virtual ~addressAppointment();
    addressAppointment& operator=(const addressAppointment& other);
    virtual addressAppointment *dup() const {return new addressAppointment(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual int getFirstAddress() const;
    virtual void setFirstAddress(int firstAddress);
    virtual int getLastAddress() const;
    virtual void setLastAddress(int lastAddress);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const addressAppointment& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, addressAppointment& obj) {obj.parsimUnpack(b);}


#endif // ifndef __ADDRESS_APPOINTMENT_M_H

